### ISSUE TITLE
Modify behavior to "Opt-in"

### ISSUE THREAD

**Issue by ingochris** [Crystal-Development/reddit-rice-bot#1]
Dear @Crystal-Development,

The current iteration of rice-bot is filling up threads on subs with spam while providing not very useful contributions to the reddit community. Therefore, please do consider changing the bot to subreddit "Opt-in" while under development. Cheers! 😺 

Best regards,
Christopher Ngo

**Comment by chrisbdaemon** [comment]
+1

**Comment by Manuel-K** [comment]
The bot should definitely be Opt-In.

Take a look at this post: https://www.reddit.com/r/borussiadortmund/comments/7hpgxn/milli_out_for_the_next_months_undifined/dqszauj/

The bot adds a happy smiley to a discussion of an injury and then it keeps reacting to it's own name spamming “Heh.”.

**Comment by ingochris** [comment]
Gee, that's some infinite loop, @Manuel-K. I'm glad we have all medical, injury, or pain related posts outlawed in our sub (/r/bodyweightfitness). I think the bot was spamming up our diet discussions.

**Comment by Stebulous** [comment]
Will do that! I apologize for any inconvenience. - The problem with it responding to its own name has since been fixed, thanks.
